// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCww8ieewfdRCfieyPtujbuvvLxl62TZGA',
    appId: '1:1033205244616:web:130a98019c7e4ec667bbfd',
    messagingSenderId: '1033205244616',
    projectId: 'travel-journal-saathi',
    authDomain: 'travel-journal-saathi.firebaseapp.com',
    storageBucket: 'travel-journal-saathi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaN8XxQpgX-R9NuZa9Ra7e2bwVgkyp-jo',
    appId: '1:1033205244616:android:df5046fd62b7dad067bbfd',
    messagingSenderId: '1033205244616',
    projectId: 'travel-journal-saathi',
    storageBucket: 'travel-journal-saathi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpB7OOxWHhpmH6N2nEVjedBaPP6wXEp70',
    appId: '1:1033205244616:ios:5eb12d150e54aec567bbfd',
    messagingSenderId: '1033205244616',
    projectId: 'travel-journal-saathi',
    storageBucket: 'travel-journal-saathi.appspot.com',
    iosClientId:
        '1033205244616-pdsekmts75m5auas3pv2nes14ga1c9r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelJournal',
  );
}
